server:
  port: 12061
spring:
  application:
    name: service1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_test_1?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  main:
    allow-circular-references: true
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12060/eureka/

logging:
  level:
    io.seata: debug

seata:
  tx-service-group: default_tx_group
  service:
    grouplist:
      default: 127.0.0.1:11091
    vgroup-mapping:
      default_tx_group: default
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:12060/eureka/
  config:
    type: file

